name = "ManifoldFlows"
uuid = "c8646671-1be4-4583-91cc-fa66bfc52ab1"
authors = ["Ben Murrell <murrellb@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
